spring:
  redis:
    port: 6379
    host: localhost

  application:
    name: springWithMongoDb


  data:
    mongodb:
      uri: mongodb+srv://Shubham_L:MH14jt9445$@springtest.fosgxpw.mongodb.net/?retryWrites=true&w=majority&appName=springTest
      database: testSpring
      auto-index-creation: true

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: shubhamsendermail@gmail.com
    password: nutf xksp fonc xlvl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.shubham.mongoDB.model
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='KBCYQUW5AMH2R3JX' password='cfltEbMuH3zEWHZ92otxtyKhuK30VyvpV/9hLopvn+1+HExo1eun72Gn6MEC3RrQ';
      session:
        timeout:
          ms: 45000

wether:
  api:
    key: ba722c45bcde4812b6a62205251907


